### ISSUE TITLE
ProGraML package breaks with recent DGL api changes

### ISSUE THREAD

**Issue by m-atalla** [ChrisCummins/ProGraML#213]
## 🐛 Bug

Hi, I'm following the example shown in the README, but I am getting the following error when I attempt to import programl:
```python
>>> import programl as pg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/m/code/tinkervenv/lib/python3.11/site-packages/programl/__init__.py", line 55, in <module>
    from programl.transform_ops import to_dgl, to_dot, to_json, to_networkx
  File "/home/m/code/tinker/venv/lib/python3.11/site-packages/programl/transform_ops.py", line 25, in <module>
    from dgl.heterograph import DGLHeteroGraph
ImportError: cannot import name 'DGLHeteroGraph' from 'dgl.heterograph' (/home/m/code/tinker/venv/lib/python3.11/site-packages/dgl/heterograph.py)
```

## To Reproduce

1. Create a virtual environment.
1.  Run the following command to install `programl`: 
```bash
pip install -U programl
```
3.  Open a Python shell and attempt to import programl package:
````bash
>>> import programl
````

## Expected behavior

The package should be imported without any errors.

## Environment

- ProGraML version: **0.3.2**
- How you installed ProGraML: **pip**
- OS: **Linux 6.1.37-lts**, EndeavourOS
- Python version: **3.11.3**
- Versions of any other relevant libraries: **dgl-1.1.1**

## Additional context
Using `pip freeze | grep dgl`  to inspect the installed version is `dgl==1.1.1` which has breaking changing in the `DGLHeteroGraph` API. I have also tried to manually downgrading **dgl** and got the following error:
```bash
$ pip install dgl==0.6.1
ERROR: Could not find a version that satisfies the requirement dgl==0.6.1 (from versions: 0.1.0, 0.1.2, 0.1.3, 1.0.0, 1.0.1, 1.0.4, 1.1.0, 1.1.1)
ERROR: No matching distribution found for dgl==0.6.1
```
which confirms that dgl-0.6.1 doesn't include a distributed package for Python 3.11

**Comment by m-atalla** [comment]
Just as a follow up on the bug report, I have been able to reproduce the bug on another machine that has Python 3.8.16 installed. However, I was able to manually downgrade **dgl** to version 0.6.1 which allowed **programl** to work on that machine. Therefore, I can safely assume that the problem persists across multiple Python versions right after a `pip install` and might require manually downgrading DGL to work. That is, if there is a package available for your Python installation (dgl>=0.6.1 or < 0.9).

I think I have narrowed this problem down pretty well, and I will have a pull request ready with a fix shortly. 

Best regards,
Mohamed

**Comment by zedong-peng** [comment]
Hi, I have the same problem. On ubuntu20.04, even after downgrading dgl can't run properly.

```bash
conda create --name env2 python=3.8.16
pip install -U programl
pip uninstall dgl
pip install dgl==0.6.1
```

ERROR info:

```bash
>>> import programl as pg
Traceback (most recent call last):
  File "/home/pengzd/programl/1.py", line 1, in <module>
    import programl as pg
  File "/home/pengzd/miniconda3/lib/python3.12/site-packages/programl/__init__.py", line 55, in <module>
    from programl.transform_ops import to_dgl, to_dot, to_json, to_networkx
  File "/home/pengzd/miniconda3/lib/python3.12/site-packages/programl/transform_ops.py", line 25, in <module>
    from dgl.heterograph import DGLHeteroGraph
ImportError: cannot import name 'DGLHeteroGraph' from 'dgl.heterograph' (/home/pengzd/miniconda3/lib/python3.12/site-packages/dgl/heterograph.py)
```

**Comment by m-atalla** [comment]
I think you forgot to activate your new conda env there, the error info you shared shows error for **3.12** python installation.
