### ISSUE TITLE
timeout is a platform specific command

### ISSUE THREAD

**Issue by Zacharias030** [ChrisCummins/ProGraML#52]
```
(base) ➜  chris_phd_repo git:(master) bazel run //deeplearning/ml4pl/graphs/unlabelled/llvm2graph -- < /tmp/foo.ll
INFO: Analyzed target //deeplearning/ml4pl/graphs/unlabelled/llvm2graph:llvm2graph (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //deeplearning/ml4pl/graphs/unlabelled/llvm2graph:llvm2graph up-to-date:
  bazel-bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph
INFO: Elapsed time: 0,455s, Critical Path: 0,15s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.py", line 64, in <module>
    app.Run(Main)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 168, in Run
    RunWithArgs(RunWithoutArgs)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 144, in RunWithArgs
    absl_app.run(DoMain, argv=argv)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/pypi__absl_py_0_7_0/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/pypi__absl_py_0_7_0/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 141, in DoMain
    main(argv)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 166, in RunWithoutArgs
    main()
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.py", line 59, in Main
    g = builder.Build(bytecode, FLAGS.opt)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/graph_builder.py", line 91, in Build
    return self._Build(bytecode, tag_hook)
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/graph_builder.py", line 106, in _Build
    bytecode, opt_path=self.opt
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/compilers/llvm/opt_util.py", line 219, in DotCallGraphAndControlFlowGraphsFromBytecode
    lambda name: name != "callgraph.dot",
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/compilers/llvm/opt_util.py", line 162, in DotGraphsFromBytecode
    opt=opt_path,
  File "/private/var/tmp/_bazel_Zacharias/7fe3063fd5d91d7b28baf77dd699e6ca/execroot/phd/bazel-out/darwin-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/compilers/llvm/opt.py", line 543, in Exec
    universal_newlines=universal_newlines,
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.6/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'timeout': 'timeout'
```

https://stackoverflow.com/questions/3504945/timeout-command-on-mac-os-x

:/

**Comment by ChrisCummins** [comment]
Yep, the SO question you linked has the answer

We depend on GNU coreutils and related packages:
https://github.com/ChrisCummins/ProGraML/blob/master/DEPS.txt#L4-L19

**Comment by ChrisCummins** [comment]
Python 3.7 has added a `timeout` arg to Popen which looks like it would make a suitable replacement, but I'm not ready to bump the python dependency from 3.6 just yet
https://docs.python.org/3.7/library/subprocess.html

**Comment by ChrisCummins** [comment]
Closing as the dependency on GNU coreutils is specified in DEPS.txt and documented in INSTALL.md
