### ISSUE TITLE
llvm2graph still failing, even on linux.

### ISSUE THREAD

**Issue by Zacharias030** [ChrisCummins/ProGraML#53]
caused by this command:
`bazel run //deeplearning/ml4pl/graphs/unlabelled/llvm2graph -- < /tmp/foo.ll`

unfortunately,  I am really dependent on `.ll ---> programl` working :/

( the file foo.ll is printed below)

```Traceback (most recent call last):
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.py", line 64, in <module>
    app.Run(Main)
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 168, in Run
    RunWithArgs(RunWithoutArgs)
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 144, in RunWithArgs
    absl_app.run(DoMain, argv=argv)
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/pypi__absl_py_0_7_0/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/pypi__absl_py_0_7_0/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 141, in DoMain
    main(argv)
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/labm8/py/app.py", line 166, in RunWithoutArgs
    main()
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.py", line 60, in Main
    print(programl.NetworkXToProgramGraph(g))
  File "/home/zacharias/.cache/bazel/_bazel_zacharias/8d8903b3e46d3ccdc7e68a63831024b0/execroot/phd/bazel-out/k8-fastbuild/bin/deeplearning/ml4pl/graphs/unlabelled/llvm2graph/llvm2graph.runfiles/phd/deeplearning/ml4pl/graphs/programl.py", line 275, in NetworkXToProgramGraph
    node_proto.type = data["type"]
```

foo.ll
```
; ModuleID = '/scratch/talbn/classifyapp_code/train//1/40.txt.cpp'
target datalayout = "e-m:e-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%"class.std::ios_base::Init" = type { i8 }

$_ZSt3powIidEN9__gnu_cxx11__promote_2IT_T0_NS0_9__promoteIS2_Xsr3std12__is_integerIS2_EE7__valueEE6__typeENS4_IS3_Xsr3std12__is_integerIS3_EE7__valueEE6__typeEE6__typeES2_S3_ = comdat any

@_ZStL8__ioinit = internal global %"class.std::ios_base::Init" zeroinitializer, align 1
@__dso_handle = external global i8
@.str = private unnamed_addr constant [3 x i8] c"%d\00", align 1
@.str.1 = private unnamed_addr constant [4 x i8] c"%d\0A\00", align 1
@llvm.global_ctors = appending global [1 x { i32, void ()*, i8* }] [{ i32, void ()*, i8* } { i32 65535, void ()* @_GLOBAL__sub_I_40.txt.cpp, i8* null }]

define internal void @__cxx_global_var_init() #0 section ".text.startup" {
entry:
  call void @_ZNSt8ios_base4InitC1Ev(%"class.std::ios_base::Init"* @_ZStL8__ioinit)
  %0 = call i32 @__cxa_atexit(void (i8*)* bitcast (void (%"class.std::ios_base::Init"*)* @_ZNSt8ios_base4InitD1Ev to void (i8*)*), i8* getelementptr inbounds (%"class.std::ios_base::Init", %"class.std::ios_base::Init"* @_ZStL8__ioinit, i32 0, i32 0), i8* @__dso_handle) #2
  ret void
}

declare void @_ZNSt8ios_base4InitC1Ev(%"class.std::ios_base::Init"*) #0

; Function Attrs: nounwind
declare void @_ZNSt8ios_base4InitD1Ev(%"class.std::ios_base::Init"*) #1

; Function Attrs: nounwind
declare i32 @__cxa_atexit(void (i8*)*, i8*, i8*) #2

; Function Attrs: uwtable
define i32 @main() #3 {
entry:
  %retval = alloca i32, align 4
  %n = alloca i32, align 4
  %m = alloca i32, align 4
  %i = alloca i32, align 4
  %z = alloca i32, align 4
  store i32 0, i32* %retval
  %call = call i32 (i8*, ...) @scanf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str, i32 0, i32 0), i32* %n)
  store i32 0, i32* %i, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %0 = load i32, i32* %i, align 4
  %1 = load i32, i32* %n, align 4
  %cmp = icmp slt i32 %0, %1
  br i1 %cmp, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %call1 = call i32 (i8*, ...) @scanf(i8* getelementptr inbounds ([3 x i8], [3 x i8]* @.str, i32 0, i32 0), i32* %m)
  %2 = load i32, i32* %m, align 4
  %call2 = call i32 @_Z1fii(i32 1, i32 %2)
  store i32 %call2, i32* %z, align 4
  %3 = load i32, i32* %z, align 4
  %call3 = call i32 (i8*, ...) @printf(i8* getelementptr inbounds ([4 x i8], [4 x i8]* @.str.1, i32 0, i32 0), i32 %3)
  br label %for.inc

for.inc:                                          ; preds = %for.body
  %4 = load i32, i32* %i, align 4
  %inc = add nsw i32 %4, 1
  store i32 %inc, i32* %i, align 4
  br label %for.cond

for.end:                                          ; preds = %for.cond
  ret i32 0
}

declare i32 @scanf(i8*, ...) #0

; Function Attrs: uwtable
define i32 @_Z1fii(i32 %x, i32 %y) #3 {
entry:
  %x.addr = alloca i32, align 4
  %y.addr = alloca i32, align 4
  %z = alloca i32, align 4
  %t = alloca i32, align 4
  %l = alloca i32, align 4
  %p = alloca i32, align 4
  store i32 %x, i32* %x.addr, align 4
  store i32 %y, i32* %y.addr, align 4
  store i32 1, i32* %t, align 4
  store i32 0, i32* %l, align 4
  %0 = load i32, i32* %y.addr, align 4
  %call = call double @_ZSt3powIidEN9__gnu_cxx11__promote_2IT_T0_NS0_9__promoteIS2_Xsr3std12__is_integerIS2_EE7__valueEE6__typeENS4_IS3_Xsr3std12__is_integerIS3_EE7__valueEE6__typeEE6__typeES2_S3_(i32 %0, double 5.000000e-01)
  %conv = fptosi double %call to i32
  store i32 %conv, i32* %p, align 4
  %1 = load i32, i32* %x.addr, align 4
  %cmp = icmp eq i32 %1, 1
  br i1 %cmp, label %if.then, label %if.end

if.then:                                          ; preds = %entry
  store i32 2, i32* %x.addr, align 4
  br label %if.end

if.end:                                           ; preds = %if.then, %entry
  %2 = load i32, i32* %x.addr, align 4
  store i32 %2, i32* %z, align 4
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %if.end
  %3 = load i32, i32* %z, align 4
  %4 = load i32, i32* %p, align 4
  %cmp1 = icmp sle i32 %3, %4
  br i1 %cmp1, label %for.body, label %for.end

for.body:                                         ; preds = %for.cond
  %5 = load i32, i32* %y.addr, align 4
  %6 = load i32, i32* %z, align 4
  %rem = srem i32 %5, %6
  %cmp2 = icmp eq i32 %rem, 0
  br i1 %cmp2, label %land.lhs.true, label %if.end.6

land.lhs.true:                                    ; preds = %for.body
  %7 = load i32, i32* %z, align 4
  %8 = load i32, i32* %y.addr, align 4
  %cmp3 = icmp ne i32 %7, %8
  br i1 %cmp3, label %if.then.4, label %if.end.6

if.then.4:                                        ; preds = %land.lhs.true
  %9 = load i32, i32* %z, align 4
  %10 = load i32, i32* %y.addr, align 4
  %11 = load i32, i32* %z, align 4
  %div = sdiv i32 %10, %11
  %call5 = call i32 @_Z1fii(i32 %9, i32 %div)
  %12 = load i32, i32* %t, align 4
  %add = add nsw i32 %12, %call5
  store i32 %add, i32* %t, align 4
  br label %if.end.6

if.end.6:                                         ; preds = %if.then.4, %land.lhs.true, %for.body
  br label %for.inc

for.inc:                                          ; preds = %if.end.6
  %13 = load i32, i32* %z, align 4
  %inc = add nsw i32 %13, 1
  store i32 %inc, i32* %z, align 4
  br label %for.cond

for.end:                                          ; preds = %for.cond
  %14 = load i32, i32* %t, align 4
  ret i32 %14
}

declare i32 @printf(i8*, ...) #0

; Function Attrs: inlinehint nounwind uwtable
define linkonce_odr double @_ZSt3powIidEN9__gnu_cxx11__promote_2IT_T0_NS0_9__promoteIS2_Xsr3std12__is_integerIS2_EE7__valueEE6__typeENS4_IS3_Xsr3std12__is_integerIS3_EE7__valueEE6__typeEE6__typeES2_S3_(i32 %__x, double %__y) #4 comdat {
entry:
  %__x.addr = alloca i32, align 4
  %__y.addr = alloca double, align 8
  store i32 %__x, i32* %__x.addr, align 4
  store double %__y, double* %__y.addr, align 8
  %0 = load i32, i32* %__x.addr, align 4
  %conv = sitofp i32 %0 to double
  %1 = load double, double* %__y.addr, align 8
  %2 = call double @llvm.pow.f64(double %conv, double %1)
  ret double %2
}

; Function Attrs: nounwind readnone
declare double @llvm.pow.f64(double, double) #5

define internal void @_GLOBAL__sub_I_40.txt.cpp() #0 section ".text.startup" {
entry:
  call void @__cxx_global_var_init()
  ret void
}

attributes #0 = { "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+sse,+sse2" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #1 = { nounwind "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+sse,+sse2" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #2 = { nounwind }
attributes #3 = { uwtable "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+sse,+sse2" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #4 = { inlinehint nounwind uwtable "disable-tail-calls"="false" "less-precise-fpmad"="false" "no-frame-pointer-elim"="true" "no-frame-pointer-elim-non-leaf" "no-infs-fp-math"="true" "no-nans-fp-math"="true" "stack-protector-buffer-size"="8" "target-cpu"="x86-64" "target-features"="+sse,+sse2" "unsafe-fp-math"="true" "use-soft-float"="false" }
attributes #5 = { nounwind readnone }

!llvm.ident = !{!0}

!0 = !{!"clang version 3.7.1 (tags/RELEASE_371/final)"}
```

**Comment by Zacharias030** [comment]
The error itself was missing from the stacktrace:

`TypeError: 'statement' has type str, but expected one of: int, long`

**Comment by ChrisCummins** [comment]
PR attached, lemme know if it works for you :)

**Comment by Zacharias030** [comment]
So much better :)
thank you!
